"""mod dtype departure time en stage_transport

Revision ID: 214552ea6cef
Revises: 551f0f849965
Create Date: 2025-06-20 10:22:02.008373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214552ea6cef'
down_revision: Union[str, None] = '551f0f849965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
