"""nueva tabla

Revision ID: 284bcb187640
Revises: 316dece08822
Create Date: 2025-06-19 12:11:05.872757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284bcb187640'
down_revision: Union[str, None] = '316dece08822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_transports',
    sa.Column('id_transport', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_day', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('bus', 'ferry', 'train', 'flight', 'boat', 'walk', 'gondola', 'other', name='transport_mode_enum'), nullable=False),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.Column('reference_code', sa.String(length=50), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['id_day'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_transport')
    )
    op.create_index(op.f('ix_day_transports_id_day'), 'day_transports', ['id_day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_transports_id_day'), table_name='day_transports')
    op.drop_table('day_transports')
    # ### end Alembic commands ###
