"""add status_optional & FKs to activitie

Revision ID: 3d5c38480735
Revises: b818593fcd77
Create Date: 2025-07-01 11:03:43.314253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d5c38480735'
down_revision: Union[str, None] = 'b818593fcd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'duration',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('activity', 'comment',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('activity', 'status_optional',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('pending', 'confirmed', 'cancelled', name='status_optional_enum'),
               nullable=False)
    op.create_index(op.f('ix_activity_id_days'), 'activity', ['id_days'], unique=False)
    op.create_index(op.f('ix_activity_id_local_guide'), 'activity', ['id_local_guide'], unique=False)
    op.create_index(op.f('ix_activity_id_optional'), 'activity', ['id_optional'], unique=False)
    op.create_foreign_key(None, 'activity', 'local_guides', ['id_local_guide'], ['id_local_guide'])
    op.create_foreign_key(None, 'activity', 'optionals', ['id_optional'], ['id_optional'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity', 'days', ['id_days'], ['id'], ondelete='CASCADE')
    op.drop_column('activity', 'id_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('id_day', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_index(op.f('ix_activity_id_optional'), table_name='activity')
    op.drop_index(op.f('ix_activity_id_local_guide'), table_name='activity')
    op.drop_index(op.f('ix_activity_id_days'), table_name='activity')
    op.alter_column('activity', 'status_optional',
               existing_type=sa.Enum('pending', 'confirmed', 'cancelled', name='status_optional_enum'),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('activity', 'comment',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('activity', 'duration',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
