"""nuevas columnas en local_guide

Revision ID: 4810c293845c
Revises: b3d664e9faf5
Create Date: 2025-07-15 12:46:46.494934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4810c293845c'
down_revision: Union[str, None] = 'b3d664e9faf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('local_guides', 'city',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=False)
    op.create_foreign_key(None, 'local_guides', 'cities', ['city'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'local_guides', type_='foreignkey')
    op.alter_column('local_guides', 'city',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
