"""Nueva columna en circuit_stages

Revision ID: 4fb2864c729d
Revises: c6d14c8a0648
Create Date: 2025-06-06 13:07:24.695017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb2864c729d'
down_revision: Union[str, None] = 'c6d14c8a0648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuit_stages', sa.Column('city_name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_circuit_stages_city_name'), 'circuit_stages', ['city_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circuit_stages_city_name'), table_name='circuit_stages')
    op.drop_column('circuit_stages', 'city_name')
    # ### end Alembic commands ###
