"""nueva columna en activity

Revision ID: 50de0f7a1c66
Revises: f88d4917a6c0
Create Date: 2025-07-01 09:59:50.646864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50de0f7a1c66'
down_revision: Union[str, None] = 'f88d4917a6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('status_optional', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'status_optional')
    # ### end Alembic commands ###
