"""por si hay cambios 

Revision ID: 9d2a22d1fdf4
Revises: 4eb1d8061924
Create Date: 2025-06-16 10:43:06.774404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2a22d1fdf4'
down_revision: Union[str, None] = '4eb1d8061924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
