"""nuevas columnas en local_guide

Revision ID: b3d664e9faf5
Revises: 3d5c38480735
Create Date: 2025-07-15 12:35:15.059847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d664e9faf5'
down_revision: Union[str, None] = '3d5c38480735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_guides', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('local_guides', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('local_guides', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('local_guides', sa.Column('updated_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_guides', 'updated_by')
    op.drop_column('local_guides', 'updated_at')
    op.drop_column('local_guides', 'created_at')
    op.drop_column('local_guides', 'city')
    # ### end Alembic commands ###
