"""nueva estructura stage_transport

Revision ID: bd830fe5253a
Revises: 347fde46f83a
Create Date: 2025-06-19 10:45:02.832935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd830fe5253a'
down_revision: Union[str, None] = '347fde46f83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_transports', sa.Column('depart_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_transports', 'depart_time')
    # ### end Alembic commands ###
