"""initial_base

Revision ID: c6d14c8a0648
Revises: 
Create Date: 2025-06-06 11:59:59.247089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d14c8a0648'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_days', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('duration', sa.Time(), nullable=True),
    sa.Column('id_optional', sa.Integer(), nullable=True),
    sa.Column('id_local_guide', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('PAX', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant',
    sa.Column('id_assistant', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_assistant')
    )
    op.create_index(op.f('ix_assistant_id_assistant'), 'assistant', ['id_assistant'], unique=False)
    op.create_table('circuits',
    sa.Column('id_circuit', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('total_nights', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_circuit'),
    sa.UniqueConstraint('name', name='uq_circuit_name')
    )
    op.create_index(op.f('ix_circuits_id_circuit'), 'circuits', ['id_circuit'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geonames_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.CHAR(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('continent', sa.CHAR(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('needs_bus_permit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geonames_id'),
    sa.UniqueConstraint('geonames_id', name='uq_city_geonames'),
    sa.UniqueConstraint('name', 'country', 'region', name='uq_city_name_country_region')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('city_permit_requirement',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=255), nullable=False),
    sa.Column('country_name', sa.String(length=255), nullable=False),
    sa.Column('permit_needed', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_city_permit_requirement_code'), 'city_permit_requirement', ['code'], unique=False)
    op.create_table('client_group',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_clients', sa.String(length=255), nullable=True),
    sa.Column('id_group', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('packages', sa.String(length=255), nullable=True),
    sa.Column('room_type', sa.String(length=255), nullable=True),
    sa.Column('shown', sa.Boolean(), nullable=True),
    sa.Column('pax_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_group_id'), 'client_group', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id_clients', sa.Integer(), nullable=False),
    sa.Column('paternal_surname', sa.String(length=255), nullable=True),
    sa.Column('mother_surname', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('second_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('passport', sa.String(length=255), nullable=True),
    sa.Column('vtc_passport', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_clients')
    )
    op.create_index(op.f('ix_clients_id_clients'), 'clients', ['id_clients'], unique=False)
    op.create_table('clients_room',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_days', sa.String(length=255), nullable=True),
    sa.Column('room_composition_id', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('days',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_group', sa.String(length=255), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('ferry', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id_driver', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('circuit', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_driver')
    )
    op.create_table('ferry',
    sa.Column('ferry_id', sa.Integer(), nullable=False),
    sa.Column('id_days', sa.String(length=255), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('reservation_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('ferry', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ferry_id')
    )
    op.create_table('group',
    sa.Column('id_group', sa.String(length=255), nullable=False),
    sa.Column('id_guide', sa.Integer(), nullable=True),
    sa.Column('id_transport', sa.String(length=255), nullable=True),
    sa.Column('id_assistant', sa.Integer(), nullable=True),
    sa.Column('assistant_id_2', sa.Integer(), nullable=True),
    sa.Column('id_operations', sa.Integer(), nullable=True),
    sa.Column('id_responsible_hotels', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('initial_flight', sa.String(length=255), nullable=True),
    sa.Column('datetime_initial_flight', sa.DateTime(), nullable=True),
    sa.Column('end_flight', sa.String(length=255), nullable=True),
    sa.Column('datetime_end_flight', sa.DateTime(), nullable=True),
    sa.Column('IGA_circuit', sa.String(length=255), nullable=True),
    sa.Column('IGA_option', sa.String(length=255), nullable=True),
    sa.Column('PAX', sa.Integer(), nullable=True),
    sa.Column('QR', sa.Boolean(), nullable=True),
    sa.Column('circuit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.create_index(op.f('ix_group_id_group'), 'group', ['id_group'], unique=False)
    op.create_table('guide_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_guide', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id_group', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guides',
    sa.Column('id_guide', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('passaport', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_guide')
    )
    op.create_table('hotel',
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_1', sa.String(length=255), nullable=True),
    sa.Column('phone_2', sa.String(length=255), nullable=True),
    sa.Column('phone_3', sa.String(length=255), nullable=True),
    sa.Column('mail_1', sa.String(length=255), nullable=True),
    sa.Column('mail_2', sa.String(length=255), nullable=True),
    sa.Column('mail_3', sa.String(length=255), nullable=True),
    sa.Column('agreements', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_hotel')
    )
    op.create_index(op.f('ix_hotel_id_hotel'), 'hotel', ['id_hotel'], unique=False)
    op.create_table('hotel_reservation',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_hotel', sa.Integer(), nullable=True),
    sa.Column('id_group', sa.String(length=255), nullable=True),
    sa.Column('id_day', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('hour_check_in', sa.Time(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('hour_check_out', sa.Time(), nullable=True),
    sa.Column('PAX', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('total_to_pay', sa.FLOAT(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('rooming_list', sa.Boolean(), nullable=True),
    sa.Column('pro_forma', sa.Boolean(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_done_date', sa.Date(), nullable=True),
    sa.Column('payed_by', sa.String(length=255), nullable=True),
    sa.Column('factura', sa.Boolean(), nullable=True),
    sa.Column('iga', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels_rooms',
    sa.Column('id_room', sa.Integer(), nullable=False),
    sa.Column('id_hotel', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('pax', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_room')
    )
    op.create_index(op.f('ix_hotels_rooms_id_room'), 'hotels_rooms', ['id_room'], unique=False)
    op.create_table('local_guides',
    sa.Column('id_local_guide', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_local_guide')
    )
    op.create_index(op.f('ix_local_guides_id_local_guide'), 'local_guides', ['id_local_guide'], unique=False)
    op.create_table('operations',
    sa.Column('id_operation', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_operation')
    )
    op.create_table('optional_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('id_activity', sa.String(length=255), nullable=True),
    sa.Column('id_optionals', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('updated_purchase_date', sa.DateTime(), nullable=True),
    sa.Column('place_of_purchase', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optionals',
    sa.Column('id_optional', sa.Integer(), nullable=False),
    sa.Column('id_stage', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('activity_time', sa.Time(), nullable=True),
    sa.Column('adult_price', sa.Float(), nullable=True),
    sa.Column('minor_price', sa.Float(), nullable=True),
    sa.Column('min_pax', sa.Integer(), nullable=True),
    sa.Column('max_pax', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_user_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_optional')
    )
    op.create_index(op.f('ix_optionals_id_optional'), 'optionals', ['id_optional'], unique=False)
    op.create_table('packages',
    sa.Column('id_packages', sa.Integer(), nullable=False),
    sa.Column('id_circuit', sa.Integer(), nullable=True),
    sa.Column('id_stage', sa.Integer(), nullable=True),
    sa.Column('id_optional', sa.Integer(), nullable=True),
    sa.Column('package_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_packages')
    )
    op.create_table('permit',
    sa.Column('id_permit', sa.String(length=255), nullable=False),
    sa.Column('permit_date', sa.Date(), nullable=True),
    sa.Column('permit_number', sa.String(length=255), nullable=True),
    sa.Column('managed_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('payed_with', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_permit')
    )
    op.create_table('responsables_hotels',
    sa.Column('id_responsible_hotels', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_responsible_hotels')
    )
    op.create_table('rooms_composition',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_room', sa.Integer(), nullable=True),
    sa.Column('room_number', sa.String(length=255), nullable=True),
    sa.Column('room_type', sa.String(length=255), nullable=True),
    sa.Column('check_in_date', sa.DateTime(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('complement', sa.Float(), nullable=True),
    sa.Column('complement_currency', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport',
    sa.Column('id_transport', sa.String(length=255), nullable=False),
    sa.Column('id_driver', sa.Integer(), nullable=True),
    sa.Column('bus', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.String(length=255), nullable=True),
    sa.Column('status_bus', sa.String(length=255), nullable=True),
    sa.Column('parking_heathrow', sa.Boolean(), nullable=True),
    sa.Column('parking_update_datetime', sa.DateTime(), nullable=True),
    sa.Column('parking_user_id', sa.String(length=255), nullable=True),
    sa.Column('pass_paris', sa.Boolean(), nullable=True),
    sa.Column('pass_paris_update_datetime', sa.DateTime(), nullable=True),
    sa.Column('pass_paris_user_id', sa.String(length=255), nullable=True),
    sa.Column('voucher_vce_florence', sa.Boolean(), nullable=True),
    sa.Column('voucher_update_datetime', sa.DateTime(), nullable=True),
    sa.Column('voucher_user_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_transport')
    )
    op.create_index(op.f('ix_transport_id_transport'), 'transport', ['id_transport'], unique=False)
    op.create_table('transport_company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('circuit_stages',
    sa.Column('id_stage', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_circuit', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['id_circuit'], ['circuits.id_circuit'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_stage'),
    sa.UniqueConstraint('id_circuit', 'stage_order', name='uq_stage_order')
    )
    op.create_index(op.f('ix_circuit_stages_city_id'), 'circuit_stages', ['city_id'], unique=False)
    op.create_index(op.f('ix_circuit_stages_id_circuit'), 'circuit_stages', ['id_circuit'], unique=False)
    op.create_table('stage_transports',
    sa.Column('id_transport', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_stage', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('bus', 'ferry', 'train', 'flight', 'boat', 'walk', 'other', 'gondola', name='transport_mode_enum'), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('transport_code', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['id_stage'], ['circuit_stages.id_stage'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_transport')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_transports')
    op.drop_index(op.f('ix_circuit_stages_id_circuit'), table_name='circuit_stages')
    op.drop_index(op.f('ix_circuit_stages_city_id'), table_name='circuit_stages')
    op.drop_table('circuit_stages')
    op.drop_table('transport_company')
    op.drop_index(op.f('ix_transport_id_transport'), table_name='transport')
    op.drop_table('transport')
    op.drop_table('rooms_composition')
    op.drop_table('responsables_hotels')
    op.drop_table('permit')
    op.drop_table('packages')
    op.drop_index(op.f('ix_optionals_id_optional'), table_name='optionals')
    op.drop_table('optionals')
    op.drop_table('optional_purchase')
    op.drop_table('operations')
    op.drop_index(op.f('ix_local_guides_id_local_guide'), table_name='local_guides')
    op.drop_table('local_guides')
    op.drop_index(op.f('ix_hotels_rooms_id_room'), table_name='hotels_rooms')
    op.drop_table('hotels_rooms')
    op.drop_table('hotel_reservation')
    op.drop_index(op.f('ix_hotel_id_hotel'), table_name='hotel')
    op.drop_table('hotel')
    op.drop_table('guides')
    op.drop_table('guide_availability')
    op.drop_index(op.f('ix_group_id_group'), table_name='group')
    op.drop_table('group')
    op.drop_table('ferry')
    op.drop_table('drivers')
    op.drop_table('days')
    op.drop_table('clients_room')
    op.drop_index(op.f('ix_clients_id_clients'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_client_group_id'), table_name='client_group')
    op.drop_table('client_group')
    op.drop_index(op.f('ix_city_permit_requirement_code'), table_name='city_permit_requirement')
    op.drop_table('city_permit_requirement')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_circuits_id_circuit'), table_name='circuits')
    op.drop_table('circuits')
    op.drop_index(op.f('ix_assistant_id_assistant'), table_name='assistant')
    op.drop_table('assistant')
    op.drop_table('activity')
    # ### end Alembic commands ###
