"""nueva tabla tarifas guias locales

Revision ID: e937606ac453
Revises: bef1acc65b3e
Create Date: 2025-08-04 13:45:01.828740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e937606ac453'
down_revision: Union[str, None] = 'bef1acc65b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_guides', 'tariff')
    op.drop_column('local_guides', 'tour_types')
    op.drop_column('local_guides', 'tariff_type')
    op.drop_column('local_guides', 'max_pax')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_guides', sa.Column('max_pax', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('local_guides', sa.Column('tariff_type', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('local_guides', sa.Column('tour_types', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('local_guides', sa.Column('tariff', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'local_guides', type_='foreignkey')
    # ### end Alembic commands ###
