"""nuevas columnas local guides

Revision ID: f1b86d88e471
Revises: 2b231f1ad546
Create Date: 2025-08-01 10:31:52.208599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b86d88e471'
down_revision: Union[str, None] = '2b231f1ad546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'hotel', 'cities', ['id_city'], ['id'])
    op.add_column('local_guides', sa.Column('tariff', sa.FLOAT(), nullable=True))
    op.add_column('local_guides', sa.Column('tariff_type', sa.String(length=255), nullable=True))
    op.add_column('local_guides', sa.Column('max_pax', sa.Integer(), nullable=True))
    op.add_column('local_guides', sa.Column('tour_types', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_guides', 'tour_types')
    op.drop_column('local_guides', 'max_pax')
    op.drop_column('local_guides', 'tariff_type')
    op.drop_column('local_guides', 'tariff')
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    # ### end Alembic commands ###
