"""nueva columna en activity

Revision ID: f88d4917a6c0
Revises: 078a3f10b76d
Create Date: 2025-06-30 14:58:27.123562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88d4917a6c0'
down_revision: Union[str, None] = '078a3f10b76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_permit_requirement',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=255), nullable=False),
    sa.Column('country_name', sa.String(length=255), nullable=False),
    sa.Column('permit_needed', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_city_permit_requirement_code'), 'city_permit_requirement', ['code'], unique=False)
    op.add_column('activity', sa.Column('reservation_n', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'reservation_n')
    op.drop_index(op.f('ix_city_permit_requirement_code'), table_name='city_permit_requirement')
    op.drop_table('city_permit_requirement')
    # ### end Alembic commands ###
