"""add status_optional & FKs to activities

Revision ID: fcb13b21a2dc
Revises: 50de0f7a1c66
Create Date: 2025-07-01 10:52:59.857118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fcb13b21a2dc'
down_revision: Union[str, None] = '50de0f7a1c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('id_day', sa.String(length=255), nullable=False))
    op.add_column('activity', sa.Column('pax', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('activity', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('activity', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.alter_column('activity', 'id_optional',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('activity', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('activity', 'time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('activity', 'duration',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('activity', 'comment',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('activity', 'status_optional',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('pending', 'confirmed', 'cancelled', name='status_optional_enum'),
               nullable=False)
    op.create_index(op.f('ix_activity_id_day'), 'activity', ['id_day'], unique=False)
    op.create_index(op.f('ix_activity_id_local_guide'), 'activity', ['id_local_guide'], unique=False)
    op.create_index(op.f('ix_activity_id_optional'), 'activity', ['id_optional'], unique=False)
    op.create_foreign_key(None, 'activity', 'optionals', ['id_optional'], ['id_optional'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity', 'local_guides', ['id_local_guide'], ['id_local_guide'])
    op.create_foreign_key(None, 'activity', 'days', ['id_day'], ['id'], ondelete='CASCADE')
    op.drop_column('activity', 'id_days')
    op.drop_column('activity', 'PAX')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('PAX', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('id_days', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_index(op.f('ix_activity_id_optional'), table_name='activity')
    op.drop_index(op.f('ix_activity_id_local_guide'), table_name='activity')
    op.drop_index(op.f('ix_activity_id_day'), table_name='activity')
    op.alter_column('activity', 'status_optional',
               existing_type=sa.Enum('pending', 'confirmed', 'cancelled', name='status_optional_enum'),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('activity', 'comment',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('activity', 'duration',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('activity', 'time',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('activity', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('activity', 'id_optional',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('activity', 'updated_by')
    op.drop_column('activity', 'updated_at')
    op.drop_column('activity', 'created_at')
    op.drop_column('activity', 'pax')
    op.drop_column('activity', 'id_day')
    # ### end Alembic commands ###
